---
extends:
  - "@commitlint/config-conventional"
rules:
  header-max-length:
    - 2
    - always
    - 96
  type-enum:
    - 2
    - always
    - - build
      - ui
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - format
      - test
      - chroe
